platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'AdFixusMobileFrameworkTest' do
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK', '9.1.0' # Require for Google Ads
  pod 'AdFixusMobileFramework', :podspec => "https://raw.githubusercontent.com/AdFixus/AdFixusMobileFramework/main/Staging/1.0.0/AdFixusMobileFramework-Staging-1.0.0.podspec"
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          if !config.base_configuration_reference.nil? && !config.base_configuration_reference.real_path.nil?
            puts "methods #{config.base_configuration_reference.methods}" 
            xcconfig_path = config.base_configuration_reference.real_path
            xcconfig = File.read(xcconfig_path)
            new_xcconfig = xcconfig.sub('-framework "GoogleMobileAds"', '')
            File.open(xcconfig_path, "w") { |file| file << new_xcconfig }
          end
        end
      end
end